version: '3.8'
services:
  backend:
    build: ./backend-go
    ports:
      - "8080:8080"

  frontend:
    build: ./frontend-react
    # No need to expose ports here as Nginx will serve the frontend

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - frontend
      - backend
